### ISSUE TITLE
BENCHMARK!!!!!!!!!!!!

### ISSUE THREAD

**Issue by johannpistorius** [APP-RS-OC-Polytech-2020/Custodia#7]
Est-ce que vous avez fait les benchmarks?

Voici un site expliquant le benchmarking:
[https://www.performance-publique.budget.gouv.fr/sites/performance_publique/files/files/documents/performance/controle_gestion/analyse_comparative/concepts_et_methodologie/Guide_methodologique_benchmarking_Nevaoconseil_2005.pdf](url)

**Comment by AdrienRybarczyk** [comment]
C'est pour @Crazyduino
